server:
  port: 20010
  servlet: 
    session:
      timeout: 7200 
      
spring:
  application:
    name: mongoStudy
  session:
    store-type: mongodb
  devtools:
    restart:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jmx:
    enabled: true 
    
logging: 
  level: 
    root: info

custom:
  #nginx: /etc/nginx/nginx.conf
  nginx: E:/nginx-1.17.10/conf/nginx.conf
  admin:
    name: admin
    pass: admin
