server:
  port: 20010
  servlet: 
    session:
      timeout: 7200 
      
spring:
  application:
    name: nginx配置器
  session:
    store-type: jdbc
  devtools:
    restart:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jmx:
    enabled: true 
  data:
    sqlite:
      package: com.cym.model
      print: true

  datasource:
    type: mysql
    url: jdbc:mysql://10.39.3.92:3306/test
    username: root
    password: 1qaz2wsx
#   type: sqlite
#   package: com.cym.model
	
logging: 
  level: 
    root: info

custom:
  nginx: E:/nginx-1.17.10/conf/nginx.conf
  admin:
    name: admin
    pass: admin